### ISSUE TITLE
Submit New GPT - Ask Dr. Andrew Huberman

### ISSUE THREAD

**Issue by jyboy** [Anil-matcha/Awesome-GPT-Store#10]
*Name*: Ask Dr. Andrew Huberman
*Description*: Maximize your productivity, physical and mental health with neuroscience. Trained with all the podcast episodes from Huberman Lab.
*Link*: https://chat.openai.com/g/g-1xC65osMP-ask-dr-andrew-huberman
*Classification*: It should be related to *Fitness and Health*.

**Comment by Anil-matcha** [comment]
Merged
