### ISSUE TITLE
New GPTs Submit: PC Builder GPT

### ISSUE THREAD

**Issue by HeyitsRadinn** [Anil-matcha/Awesome-GPT-Store#118]
🖥️ PC Builder GPT
   - I'm PC Builder GPT, your tech-savvy virtual friend who offers expert and approachable advice on building PCs, complete with up-to-date pricing.
   - [Chat now](https://chat.openai.com/g/g-gh7PDdmmd-pc-builder-gpt)
   - Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

**Comment by Anil-matcha** [comment]
Merged
