### ISSUE TITLE
New Entertainment GPTs

### ISSUE THREAD

**Issue by ItaiLeibowitz** [Anil-matcha/Awesome-GPT-Store#123]
Story Buddy:
A creative guide for kids to build and illustrate bedtime stories.
https://chat.openai.com/g/g-2k7EGyB1p-story-buddy

Dear Gabrielle: 
Sassy, warm-hearted advice columnist offering humorous, insightful guidance.
https://chat.openai.com/g/g-PYchE5klx-dear-gabrielle

Griselda:
A mystical tarot guide
https://chat.openai.com/g/g-BsLFiAtkF-griselda

Serge:
A jaded French caricaturist who draws caricatures in exchange for compliments.
https://chat.openai.com/g/g-JiFqpfbTa-serge

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
