### ISSUE TITLE
Please add - personal Carbon footprint count guide tool 

### ISSUE THREAD

**Issue by Theatrix2020** [Anil-matcha/Awesome-GPT-Store#125]
Personal carbon count calculator guide : [Carbon count guide](https://chat.openai.com/g/g-269eJfz9f-carbon-count-guide)

**Comment by Theatrix2020** [comment]
@Anil-matcha Thank you for adding AFYA to the list. Will you please add my other projects on your list please? I have these and a couple more under my account.

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
