### ISSUE TITLE
GPT: Coding Dojo

### ISSUE THREAD

**Issue by leventarican** [Anil-matcha/Awesome-GPT-Store#127]
Coding Dojo - https://chat.openai.com/g/g-gYDYDOBV6-coding-dojo
Coding Dojo Master for Python challenges and motivation.

**Comment by leventarican** [comment]
Maestro - https://chat.openai.com/g/g-EFwcq7NO6-maestro
Creates simple music and download it as .wav file.

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
