### ISSUE TITLE
Seat Seeker GPT

### ISSUE THREAD

**Issue by HeyitsRadinn** [Anil-matcha/Awesome-GPT-Store#13]
Efficient and detailed in finding the right seating.

Seat Seeker excels in efficiently assisting users to find public seating with specific amenities, using their approximate location. It combines the thoroughness of its initial approach with the brevity of the second, asking pertinent questions about Wi-Fi, outlets, and ambiance preferences like quiet study areas or social spaces. This balanced approach ensures Seat Seeker provides concise yet comprehensive responses, tailored to user needs. It maintains a friendly tone, while focusing on delivering quick, relevant suggestions.

https://chat.openai.com/g/g-3AQM5NfzA-seat-seeker

**Comment by Anil-matcha** [comment]
Merged
