### ISSUE TITLE
Please add OCR

### ISSUE THREAD

**Issue by docduo** [Anil-matcha/Awesome-GPT-Store#130]
**OCR**

Extract text and content from images or PDF documents

https://chat.openai.com/g/g-wETMBcESv-ocr

You can add the following to the productivity section for example 🙏🏻 
```
- [OCR](https://chat.openai.com/g/g-wETMBcESv-ocr) - Extract text and content from images or PDF documents by [ocr.chat](https://get.ocr.chat/gpt)
```

- [PR: https://github.com/taranjeet/awesome-gpts/pull/45](https://github.com/Anil-matcha/Awesome-GPT-Store/pull/128)

**Comment by Anil-matcha** [comment]
Merged
