### ISSUE TITLE
New GPT Submission: City Pal

### ISSUE THREAD

**Issue by ranjeevn16** [Anil-matcha/Awesome-GPT-Store#148]
City Pal is a handy personalized city guide that helps you find the latest happenings in your city curated to your personality and interests! Whether you're new to a city and looking to get familiar or just looking for a change of pace for the weekend this is the ultimate guide for you!
https://chat.openai.com/g/g-uMwvSPpwD-city-pal

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
