### ISSUE TITLE
Please add: GameGuru

### ISSUE THREAD

**Issue by sspicola** [Anil-matcha/Awesome-GPT-Store#156]
GameGuru: https://chat.openai.com/g/g-iyT5Abyc3-gameguru

GameGuru is a specialized video game recommendation bot. Its purpose is to help you discover your next favorite game. It has a wide knowledge of video games across various genres and platforms, including both popular mainstream titles and hidden indie gems. Here's how it can assist you:

Personalized Recommendations: It can provide tailored game suggestions based on your individual preferences, such as genre, platform, and past gaming experiences. To make sure its recommendations are spot-on, it will ask a few questions about your gaming tastes and history.

Expansive Game Knowledge: Whether you're into action, RPGs, strategy, or any other genre, it has recommendations ready. It also covers different gaming platforms, so whether you play on PC, console, or mobile, it has you covered.

Deals and Discounts: If you're interested in finding the best deals for a particular game, it can use an API to fetch current sale information. It will provide you with a link to access these deals directly.

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
