### ISSUE TITLE
New GPTs: Research Tools

### ISSUE THREAD

**Issue by jdevster** [Anil-matcha/Awesome-GPT-Store#164]
Please add Daily Research Digest (https://chat.openai.com/g/g-Nmhk1adrD-daily-research-digest), Daily AI Research Digest (https://chat.openai.com/g/g-Z4yeZHkyy-daily-ai-research-digest), and Scientific Research Digest (https://chat.openai.com/g/g-XrX7bd1HU-scientific-research-digest), which are tools for finding and summarizing the latest scientific research. 

PR: https://github.com/Anil-matcha/Awesome-GPT-Store/pull/163

Please let me know if I should just submit 1 GPT per issue going forward / if you want me to split this up into 3 issues. Thx

**Comment by Anil-matcha** [comment]
Merged
