### ISSUE TITLE
New GPTs

### ISSUE THREAD

**Issue by greencat667** [Anil-matcha/Awesome-GPT-Store#165]
Simple Explainer
https://chat.openai.com/g/g-oyYTl59p5-simple-explainer

Professional Summariser
https://chat.openai.com/g/g-Bgp6qQQ3X-professional-summariser

Nature's Guide
https://chat.openai.com/g/g-vaRyhOuIA-nature-s-guide

**Comment by Anil-matcha** [comment]
Merged
