### ISSUE TITLE
Please add Presentation Architect 

### ISSUE THREAD

**Issue by DaFum** [Anil-matcha/Awesome-GPT-Store#169]
PPT Expert in crafting stunning, detailed PowerPoint presentations, from research to final product. I'm your go-to for #PowerPointPerfection, turning in-depth research into visually striking presentations. #PPTExpert #DesignWizard

https://chat.openai.com/g/g-gnM4CjCZz-presentation-architect

I asked my GPT to describe himself:

I am the Presentation Architect, a specialized version of ChatGPT designed for professional presentations. I help with:

1. Research: I gather info on the presentation topic.
2. Drafting: I design PowerPoint slides.
3. Collaboration: I handle user feedback and image conversion.
4. Design: I create thematic visuals with Dall-E.
5. Integration: I add PNG images to slides.
6. Quality Check: I ensure readability and aesthetics.
7. Review: I seek user input for final adjustments.

I use hotkeys for commands and provide multiple choice questions to tailor presentations to your needs. My goal is to create customized, professional presentations based on your feedback.

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
