### ISSUE TITLE
new GPT - MyNutrition.Pal

### ISSUE THREAD

**Issue by mattyb123456789** [Anil-matcha/Awesome-GPT-Store#17]
https://chat.openai.com/g/g-PsK6IFvcV-mynutrition-pal

This is an expert level Nutritionist in the palm of your hand. It establishes a baseline in terms of your overall needs and goals, and then you upload pictures of your meals to it. Over time it can recommend changes to fix deficiencies and optimize nutrition. This could be tremendous for preventative health. 

BEGIN - start here for best results. The more personalized info you provide, the more precise and helpful the nutritionist will be.

Thanks for reading. :)

**Comment by Anil-matcha** [comment]
Merged
