### ISSUE TITLE
Please add: News Bias Analyzer

### ISSUE THREAD

**Issue by davidpcahill** [Anil-matcha/Awesome-GPT-Store#179]
### News Bias Analyzer
Targeted Bias Detection with Graphing, Summarization, Categorization, Tagging, and Comprehensive Source Evaluation (Cybrix.AI)

https://chat.openai.com/g/g-9tbHB4O4r-news-bias-analyzer

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
