### ISSUE TITLE
GPTs to add

### ISSUE THREAD

**Issue by benhurley** [Anil-matcha/Awesome-GPT-Store#189]
Game Genius | Your go-to expert for gameplay walkthroughs and cheat codes.
https://chat.openai.com/g/g-12q0jqkhd-game-genius

Vinobot | Digital sommelier for specific wine bottle recs. 
https://chat.openai.com/g/g-EoBW5i2gu-vinobot

Mechanic Mate | Your virtual mechanic for diagnosing car noises, getting ready for service visits, and beyond.
https://chat.openai.com/g/g-rUgFfFwbm-mechanic-mate

Parental Wisdom | Advice for everyday questions
https://chat.openai.com/g/g-1hwxvXKWi-parental-wisdom

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
