### ISSUE TITLE
GPT To Submit: Art Companion

### ISSUE THREAD

**Issue by Nolattosio** [Anil-matcha/Awesome-GPT-Store#198]
Thanks for ad :)

Name: [Art Companion](https://chat.openai.com/g/g-1dEwOItVl-art-companion)
Description: A Guide Through the Creative and Professional Worlds of Art

Creator [@nolattosio](https://www.yuliyavladkovska.com/) 
Link: https://chat.openai.com/g/g-1dEwOItVl-art-companion

Thank you!

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
