### ISSUE TITLE
Anime Me, an anime Profile Picture Generator

### ISSUE THREAD

**Issue by stale2000** [Anil-matcha/Awesome-GPT-Store#20]
Description:  turn photos into Anime-style art

I created a profile picture generator that quickly turns you into an anime character!  It works pretty well.  

https://chat.openai.com/g/g-hXlHRbEkS-anime-me

EDIT:  Pr here:  https://github.com/Anil-matcha/Awesome-GPT-Store/pull/21

**Comment by Anil-matcha** [comment]
Merged
