### ISSUE TITLE
GPT To Submit: Tweet-Segmenter

### ISSUE THREAD

**Issue by chansey97** [Anil-matcha/Awesome-GPT-Store#204]
Tweet-Segmenter

Segment large text into tweet-sized parts with a counter to the end of each segment. 

Specifically built for twitter/x free users!

Key Features: 

- Smart Text Segmentation: Automatically segments long texts into individual tweets, maintaining readability and context.

- Preserved Formatting: Keeps the original text format, including line breaks and paragraphs.

- Sentence Integrity: Ensure the sentence integrity of each tweet as much as possible.

- Maximized Content per Tweet: Maximizes the use of Twitter's character limit for each tweet.

- Sequential Tweet Counter: Automatically adds a counter (e.g. [2/10]) at the end of each tweet.

- Double Quotation Compatibility: Double-quoted texts are accurately maintained.

Creator: [@chansey97](https://github.com/chansey97)

Link: https://chat.openai.com/g/g-tR9Zg3SfS-tweet-segmenter

It is of course an open source project: https://github.com/chansey97/Tweet-Segmenter

Screenshot:

https://github.com/chansey97/Tweet-Segmenter/assets/4015056/4ffa949a-7da1-409a-8a49-30949388e5ba

Thank you!

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same

**Comment by chansey97** [comment]
DONE.
