### ISSUE TITLE
GPT To Submit: DaVinci Resolve Assistant

### ISSUE THREAD

**Issue by IgorRidanovic** [Anil-matcha/Awesome-GPT-Store#210]
https://chat.openai.com/g/g-suSgYbcpa-davinci-resolvetm-assistant

DaVinci Resolve™ Assistant provides expert AI support for DaVinci Resolve™, Blackmagic Design Fusion™, and Fairligh™ products.

By Igor Riđanović, www.metafide.com

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
