### ISSUE TITLE
New GPTs by iter-academy.com

### ISSUE THREAD

**Issue by andrii-partola** [Anil-matcha/Awesome-GPT-Store#211]
https://chat.openai.com/g/g-RHOq7wFZT-fitness-coach
https://chat.openai.com/g/g-1nzIjWUhk-telegram-formatter
https://chat.openai.com/g/g-r6rdCl5PD-c-interview-assistant
https://chat.openai.com/g/g-KWE08yo7S-c-interview-assistant
https://chat.openai.com/g/g-B5ywsVvTx-c-interview-assistant
https://chat.openai.com/g/g-W4d6DjJ8c-java-interview-assistant
https://chat.openai.com/g/g-UOjns5Wlk-php-interview-assistant
https://chat.openai.com/g/g-2vZf22ugp-sql-interview-assistant
https://chat.openai.com/g/g-ZGBSrc360-javascript-interview-assistant
https://chat.openai.com/g/g-hdPdrSRgY-golang-interview-assistant
https://chat.openai.com/g/g-CbmwCOcW1-python-interview-assistant
https://chat.openai.com/g/g-oN8fQdL7p-swift-interview-assistant
https://chat.openai.com/g/g-kiMO5taht-manual-qa-interview-assistant
https://chat.openai.com/g/g-XtTZ6epaU-automation-qa-interview-assistant

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
