### ISSUE TITLE
GPT to submit: Fashion Advice

### ISSUE THREAD

**Issue by RehanSaif** [Anil-matcha/Awesome-GPT-Store#214]
https://chat.openai.com/g/g-xRzlK9VvK-fashion-advisor

**Key features**

1: rate outfit - based on your uploaded image, the GPT will rate it and give styling advice and optionally suggest a complementary item
2: suggest item - upload a few pictures of your current outfits and the GPT will recommend an item that will fit your style and these outfits.
3: suggest outfit - upload a picture of you and get a full outfit recommended that will suit you!

Creator:
https://twitter.com/rehans_ai_f

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
