### ISSUE TITLE
GPTs to add (500+ uses)

### ISSUE THREAD

**Issue by GuyBarel26** [Anil-matcha/Awesome-GPT-Store#217]
Programming: https://chat.openai.com/g/g-mGXmgcSla-coder-programmer-by-gb   
GPT building: https://chat.openai.com/g/g-4GO8XmZ7C-gpt-builder-by-gb   
Humanize text: https://chat.openai.com/g/g-PYS3yQ5eI-humanizer-by-gb 
Midjourney prompt generation: https://chat.openai.com/g/g-bAMnKWRpi-pro-journey-prompt-generator-by-gb 
Website building: https://chat.openai.com/g/g-KWMTEwWRN-website-builder-by-gb 
SEO optimization: https://chat.openai.com/g/g-8DMw5jH2m-seo-optimizer-by-gb 
Prompt building: https://chat.openai.com/g/g-gprKPL8z3-prompt-builder-by-gb 
AI finder: https://chat.openai.com/g/g-dZ7h9BrR1-ai-finder-by-gb 
Web designer: https://chat.openai.com/g/g-56FrcSptX-web-designer-by-gb 
Essay writer: https://chat.openai.com/g/g-b3FQDs9VR-essay-writer-by-gb 
IB (International Baccalaureate): https://chat.openai.com/g/g-qLQ6IPl45-ib-expert-by-gb 
Math: https://chat.openai.com/g/g-fuTEniPJI-math-professor-by-gb 
College essay writer: https://chat.openai.com/g/g-Cz02a3eku-college-essay-writer-by-gb 
GPT of r/GPTreview: https://chat.openai.com/g/g-RLUSGOufd-gptreview-the-official-ai-of-r-gptreview-by-gb 
Gaming performance booster: https://chat.openai.com/g/g-QZCn9xt0k-fps-booster-by-gb 
Research assistant: https://chat.openai.com/g/g-AyyK4Coy1-research-assistant-by-gb

**Comment by Anil-matcha** [comment]
Please raise a pull request for these
