### ISSUE TITLE
Need 5 GPTs added

### ISSUE THREAD

**Issue by davidpcahill** [Anil-matcha/Awesome-GPT-Store#225]
Is this list and app still being maintained? If so, please add the following GPTs:

https://chat.openai.com/g/g-9tbHB4O4r-news-bias-analyzer
https://chat.openai.com/g/g-3K6u1eRlD-crop-it
https://chat.openai.com/g/g-z2ZzMfvqv-data-only
https://chat.openai.com/g/g-mLeQhjN21-gpt-action-builder
https://chat.openai.com/g/g-TAANxtI3q-regex-crafter
https://chat.openai.com/g/g-Fz2gm6LcG-rudegpt

Source: https://cybrix.ai/gpts.html (I am the author of all above)

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
