### ISSUE TITLE
Add AI Daily Digest and a few fun GPTs.

### ISSUE THREAD

**Issue by jdevster** [Anil-matcha/Awesome-GPT-Store#227]
Add AI daily digest (https://chat.openai.com/g/g-th685hNma-ai-daily-digest), which provides the latest AI news and research. Also add some fun GPTs: 20 Questions (https://chat.openai.com/g/g-tDUzfZTxo-20-questions), Celebrity Critter Creator (https://chat.openai.com/g/g-moHqu685w-celebrity-critter-creator), T or D (https://chat.openai.com/g/g-cUz6Adczm-t-or-d), and Zodiac Chuckler (https://chat.openai.com/g/g-Coph8tZoq-zodiac-chuckler). PR: https://github.com/Anil-matcha/Awesome-GPT-Store/pull/226

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
