### ISSUE TITLE
Add GPT:[latest] FastAPI GPT

### ISSUE THREAD

**Issue by luona-dev** [Anil-matcha/Awesome-GPT-Store#230]
🤯 [latest]FastAPI GPT
An up-to-date FastAPI coding assistant of the [[latest]](https://gpts.luona.dev/gpts) family.
[Chat now](https://chat.openai.com/g/g-BhYCAfVXk-latest-fastapi-gpt)
Submit by [@luona-dev](https://github.com/luona-dev)

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
