### ISSUE TITLE
Add latest GPTs

### ISSUE THREAD

**Issue by jdevster** [Anil-matcha/Awesome-GPT-Store#233]
Add various GPTs:
[GyattGPT](https://chat.openai.com/g/g-sqEQTZpDf-gyattgpt) - GPT with Gen Z lingo
[WrongGPT](https://chat.openai.com/g/g-DhOutKD2I-wronggpt) - Answers questions confidently and incorrectly
[Celebrity Book Finder](https://chat.openai.com/g/g-AY82KxZMH-celebrity-book-finder) - Find out what celebrities are reading!
[ChatGTO](https://chat.openai.com/g/g-xk7H68HgQ-chatgto) - Your personalized poker coach. Analyze your hands using game theory optimal (GTO) principles.
[Moon Watcher](https://chat.openai.com/g/g-6saRzdc7g-moon-watcher) - I identify today's trending stocks and cryptocurrencies and explain why they're moving. Not financial advice.

Various college advisor GPTs:
[ChaatGPT](https://chat.openai.com/g/g-kwJqxVgql-chaatgpt)
[U.S. College Advisor for Ethiopian Students](https://chat.openai.com/g/g-O29TG79Q8-u-s-college-advisor-for-ethiopian-students)
[U.S. College Advisor for Japanese Students](https://chat.openai.com/g/g-3QpKtpkKn-u-s-college-advisor-for-japanese-students)
[U.S. College Advisor for South Korean Students](https://chat.openai.com/g/g-z4Dx0V5HB-u-s-college-advisor-for-south-korean-students)
[U.S. College Advisor for U.K. Students](https://chat.openai.com/g/g-fhRtsoz1Z-u-s-college-advisor-for-u-k-students)

PR: https://github.com/Anil-matcha/Awesome-GPT-Store/pull/232

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
