### ISSUE TITLE
GPT to add: BounceBan

### ISSUE THREAD

**Issue by charmgene** [Anil-matcha/Awesome-GPT-Store#235]
Link: 
https://chat.openai.com/g/g-q5uXtrvkH-bounceban-com-free-email-verification
Description:
The only email verification service that supports verifying catch-all emails. 97+% accuracy guaranteed. Free & Unlimited for ChatGPT. Tips: 1) Enter one or multiple emails for verification. 2) Enter "Gavin Lee bounceban.com" to generate and bulk verify up to 30 potential email addresses.

**Comment by Anil-matcha** [comment]
Done
