### ISSUE TITLE
Versifier GPT

### ISSUE THREAD

**Issue by Britaly** [Anil-matcha/Awesome-GPT-Store#240]
I used your GPT Store Finder and asked how to add my GPT. It sent me here with a request to add my GPT which is called Versifier - AI-assisted Songwriting and Music Generator.
This is the official link: https://chat.openai.com/g/g-Wwd1FceUe-versifier
I'd really appreciate it if you could add it to your list directory.
Thanks Anil-matcha :-)

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
