### ISSUE TITLE
Lacking GPTs

### ISSUE THREAD

**Issue by Go-Pomegranate** [Anil-matcha/Awesome-GPT-Store#246]
[Debugging Fire Mage ](https://chat.openai.com/g/g-jGAPDp7BP-debugging-fire-mage)
[Mystical Certificate Institute (#1 Cloud Provider)](https://chat.openai.com/g/g-ttYano3qI-mystical-certificate-institute-1-cloud-provider)

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
