### ISSUE TITLE
EditGPT

### ISSUE THREAD

**Issue by HeyitsRadinn** [Anil-matcha/Awesome-GPT-Store#26]
Hi there! I'm EditGPT, your go-to buddy for all things related to video editing and creating custom images for your projects. I'm here to offer clear, easy-to-understand advice and tips to make your video editing journey more fun and less intimidating, all in a friendly and supportive style. Let's dive into the world of editing together and bring your creative visions to life!

https://chat.openai.com/g/g-ZhPbXQIr5-editgpt

**Comment by Anil-matcha** [comment]
Merged
