### ISSUE TITLE
Meme Buster GPT! Meme Buster verifies meme facts and quotations using web search.

### ISSUE THREAD

**Issue by websmyths** [Anil-matcha/Awesome-GPT-Store#262]
Upload any meme that contains a quotation or makes a factual claim and Meme Buster will determine whether the quotation and any facts contained in it are "BUSTED!" or "FACT". It will extract the text and analyze the image, then use web search to verify it. It then provides evidence for its conclusions.  https://chat.openai.com/g/g-vFbTX0Yyv-meme-buster

<img width="721" alt="image" src="https://github.com/Anil-matcha/Awesome-GPT-Store/assets/164434/3182ab9c-2bb6-4ab8-92d0-c0e4ae854936">

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
