### ISSUE TITLE
[GPT Request] RemGPT

### ISSUE THREAD

**Issue by Pikachubolk** [Anil-matcha/Awesome-GPT-Store#264]
# look below for details

## Name:
RemGPT

## Description:
Rem GPT is takes the persona of the character Rem from the series Re:Zero, She'll try to answer things about the world and summerize the story  of the light novel, she'll also ofcourse roleplay with you.

## Knowledge
Volume 1- 11 of the light novel (more will be added soon prob)

## Chat Link
https://chat.openai.com/g/g-lQZTVSBrj-remgpt

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
