### ISSUE TITLE
Submit new GPT: Bespoke Portfolio

### ISSUE THREAD

**Issue by jacquelinegarrahan** [Anil-matcha/Awesome-GPT-Store#283]
<img width="953" alt="Screenshot 2023-12-24 at 9 21 00 PM" src="https://github.com/Anil-matcha/Awesome-GPT-Store/assets/25035114/63bf16bf-3ece-43fc-ab6f-b3c6890403f7">

[Bespoke Portfolio](https://chat.openai.com/g/g-YQv4dmvEh-bespoke-portfolio)

Creates custom indices with companies across verticals based on your interests.

**Comment by Anil-matcha** [comment]
Please raise a pull request for the same
