### ISSUE TITLE
Awesome GPT Store - based on https://github.com/Anil-matcha/Awesome-GPT-Store

### ISSUE THREAD

**Issue by prajwalsouza** [Anil-matcha/Awesome-GPT-Store#32]
Created [Awesome GPT Store](https://chat.openai.com/g/g-qXtRuY3gz-awesome-gpt-store) based on this repo. :)
I can read this repository via GitHub API. 

But I wondering if there was another markdown file to which anyone could write/submit/append their GPTs. 
Because I'm struggling to figure out how to make API calls to write to a repo.

**Comment by Anil-matcha** [comment]
https://raw.githubusercontent.com/Anil-matcha/Awesome-GPT-Store/main/README.md

You can just read from the raw file

**Comment by prajwalsouza** [comment]
Yeah. That's better maybe.
