### ISSUE TITLE
DeepGame - Visual Interactive Story Game

### ISSUE THREAD

**Issue by eliohead** [Anil-matcha/Awesome-GPT-Store#33]
I created a GPT called DeepGame, where you can interactively play through a story. It allows you to play in various situations as a character.
You'll decide what to do next, and based on that action AI will proceed with the story. A new image is created for each step to make the experience as immersive as possible.
[https://chat.openai.com/g/g-TzI2BlJPT-deepgame](https://chat.openai.com/g/g-TzI2BlJPT-deepgame)

**Comment by Anil-matcha** [comment]
Merged
