### ISSUE TITLE
Language Friend - Conversation Improver GPT

### ISSUE THREAD

**Issue by KRIS-UK** [Anil-matcha/Awesome-GPT-Store#37]
Here is my language GPT. I use it every day to help me learn Swedish and it has been a massive help. Hopefully someone else will find it useful. I've also included a Spanish version, which might have  more application.

https://chat.openai.com/g/g-xsnkbBK5n-swedish-friend-language-conversation-improver

https://chat.openai.com/g/g-p5dJAcoT8-spanish-friend-language-conversation-improver

Hopefully those links work ok.

**Comment by Anil-matcha** [comment]
Merged
