### ISSUE TITLE
Custom GPTs - ChessGPT code interpreter plays PyChess on a board with you 

### ISSUE THREAD

**Issue by zer0int** [Anil-matcha/Awesome-GPT-Store#38]
Here's a custom GPT [GPT4 + code interpreter] that's a ChessGPT!

But beware - the AI is Magnus C·AI·rlsen... 🤖♟️🤓
👉 [https://chat.openai.com/g/g-Vv0j2UKiS-chessgpt](url)

Simply say “Let’s start!” (or something along the lines) and it will prepare its chess environment. Use algebraic notation to play.

**Comment by Anil-matcha** [comment]
@flexagoon @oks8 Good catch! You're both absolutely right — MIT does require including the copyright notice. I've removed the "no attribution required" claim from the README. Thanks for the correction!

**Comment by flexagoon** [comment]
@Anil-matcha i think your agent broke and closed the wrong issue
