### ISSUE TITLE
Yoga Guru  and Food Guru 

### ISSUE THREAD

**Issue by learnwithaji** [Anil-matcha/Awesome-GPT-Store#40]
Hi,

Yoga Guru is a specialized GPT with a focus on Indian traditional yoga practice
https://chat.openai.com/g/g-wfn8ST75q-food-guru

Food Guru is exclusively dedicated to discussing food-related topics with concise, humorous responses.
https://chat.openai.com/g/g-wfn8ST75q-food-guru

Regards

**Comment by Anil-matcha** [comment]
Merged
