### ISSUE TITLE
New GPTs: The Shaman and DAD!

### ISSUE THREAD

**Issue by dangerpotter** [Anil-matcha/Awesome-GPT-Store#60]
Hello! I have two GPTs that I would like to add to this list. Please see below and thanks!

[The Shaman](https://chat.openai.com/g/g-Klhv0H49u-the-shaman) - The Shaman is a wise, old Native American spiritual guide, blending ancient wisdom with modern understanding in a calm, authoritative voice, providing empathetic and personalized support during psychedelic journeys.

[DAD](https://chat.openai.com/g/g-7tYB6K5F8-dad) - DAD is a digital personification of the quintessential father figure. This virtual dad offers a wide range of advice from home improvement to financial management, while maintaining a friendly, humorous personality.

**Comment by Anil-matcha** [comment]
Merged
