### ISSUE TITLE
Fact checking GPT

### ISSUE THREAD

**Issue by tevslin** [Anil-matcha/Awesome-GPT-Store#68]
https://chat.openai.com/g/g-zoALrjHHV-fact-or-fiction. can check web pages, uploaded documents, or assertions of fact as well as math. returns links to sources for fact-checking, browses so can deal with breaking news, and generates python to check math. PR is https://github.com/Anil-matcha/Awesome-GPT-Store/pull/67

**Comment by Anil-matcha** [comment]
Merged

**Comment by tevslin** [comment]
Thank you
