### ISSUE TITLE
[Add-Request] EconomicsGPT

### ISSUE THREAD

**Issue by dpeachpeach** [Anil-matcha/Awesome-GPT-Store#69]
EconomicsGPT is tailored for K-8, High school students, and Undergraduates studying Economics. Using high-quality instructional material from the internet, the University of Chicago's lectures, lecture notes, and course materials, EconomicsGPT allows students to receive high-quality personal tutoring in a subject that has primitive documentation online. EconGPT also holds a large bank of practice problems for prospective students to choose from. Just ask for a few!

[Use now](https://chat.openai.com/g/g-7McsRKuPS-economicsgpt)

**Comment by Anil-matcha** [comment]
Merged
