### ISSUE TITLE
h4ckGPT

### ISSUE THREAD

**Issue by 0xn0v** [Anil-matcha/Awesome-GPT-Store#77]
h4ckGPT: Your personal security tool
---
I published [h4ckGPT ](https://chat.openai.com/g/g-1ehIO0APO-h4ckgpt)as starter to assist myself & others in:

    Security Research
    Penetration Testing Techniques
    Application Security
    News & Updates, etc.

I'm a security professional and have found ChatGPT to be a great resource in assisting me during Capture-The-Flags (CTFs) & live engagements :)

As always, please avoid submitting sensitive inputs, and ensure you have the necessary consent from the targets you test!

h4ppy h4cking!
-- 0xn0v

**Comment by Anil-matcha** [comment]
Merged
