### ISSUE TITLE
New GPTs Submit: DJGPT

### ISSUE THREAD

**Issue by HeyitsRadinn** [Anil-matcha/Awesome-GPT-Store#94]
DJGPT 🎧
   - I'm DJGPT, your go-to AI for all things DJing and music mixing, here to guide you through the exciting world of beats and tracks!
   - [Chat now](https://chat.openai.com/g/g-NlwIQ4CSj-djgpt.)
   - Submit by [@HeyitsRadinn](https://github.com/HeyitsRadinn)

**Comment by Anil-matcha** [comment]
Merged
