### ISSUE TITLE
New GPTs Submit: Physique Coach

### ISSUE THREAD

**Issue by foraxe** [Anil-matcha/Awesome-GPT-Store#96]
💪 Physique Coach

Analyzing progress, setting goals, and giving feedback on your training plans.

[Chat now](https://chat.openai.com/g/g-nAVBYsZ93-physique-coach)
Submit by [@foraxe](https://github.com/foraxe)

**Comment by Hansdlastreet** [comment]
Share your GPTs and apply to be the GPT Of The Week  here : https://gptspedia.io ❤️

**Comment by Anil-matcha** [comment]
Merged
